name: Package exe with PyInstaller - Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Create environment and install dependencies
      run: |
        $CONDA/bin/conda env create --file environment.yml --name asciiviewer
        
    - name: Create binary
      run: |
        $CONDA/envs/asciiviewer/bin/pyinstaller --clean -y --dist ./dist/linux ./asciiviewer.spec
        
    - uses: actions/upload-artifact@v2
      with:
        name: asciiviewer
        path: ./dist/linux
