name: Package app - MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 5
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        sudo $CONDA/bin/conda env create --file environment.yml --name asciiviewer

    - name: Create macos app
      run: |
        $CONDA/envs/asciiviewer/bin/pyinstaller --windowed --clean -y --dist ./dist/macos ./asciiviewer.spec
        rm -f ./dist/macos/asciiviewer

    - uses: actions/upload-artifact@v2
      with:
        name: asciiviewer
        path: ./dist/macos
