name: Build and Release Assets

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  linux:
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        $CONDA/bin/conda env create --file environment.yml --name asciiviewer

    - name: Create binary
      run: |
        $CONDA/envs/asciiviewer/bin/pyinstaller --clean -y --dist ./dist/linux ./asciiviewer.spec

    - name: Zip binary
      run: |
        cd ./dist/linux
        zip asciiviewer-linux.zip asciiviewer

    - uses: actions/upload-artifact@v2
      with:
        name: asciiviewer-linux
        path: ./dist/linux/asciiviewer-linux.zip

  macos:
    runs-on: macos-10.15
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        sudo $CONDA/bin/conda env create --file environment.yml --name asciiviewer

    - name: Create macos app
      run: |
        $CONDA/envs/asciiviewer/bin/pyinstaller --clean -y --dist ./dist/macos ./asciiviewer.spec
        rm -rf ./dist/macos/asciiviewer

    - name: Zip binary
      run: |
        cd ./dist/macos
        zip -r asciiviewer-macos.zip .

    - uses: actions/upload-artifact@v2
      with:
        name: asciiviewer-macos
        path: ./dist/macos/asciiviewer-macos.zip

  windows:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        %CONDA%\Scripts\conda.exe env create ^
        --file environment.yml --name asciiviewer
      shell: cmd

    - name: Create binary
      run: |
        %CONDA%\envs\asciiviewer\Scripts\pyinstaller.exe ^
        --clean -y --dist .\dist\windows64 .\asciiviewer.spec
      shell: cmd

    - name: Zip binary
      run: |
        cd .\dist\windows64
        powershell Compress-Archive asciiviewer.exe asciiviewer-windows64.zip

    - uses: actions/upload-artifact@v2
      with:
        name: asciiviewer-windows64
        path: .\dist\windows64\asciiviewer-windows64.zip

  wine:
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    container:
      image: docker://cdrx/pyinstaller-windows:python3-32bit

    steps:
    - uses: actions/checkout@v2

    - name: Install zip
      run: apt-get install -y zip unzip

    - name: Install wine requirements
      run: pip install -r wine-requirements.txt

    - name: Create binary
      run: |
        python -m PyInstaller \
        --dist ./dist/windows32 \
        --onefile --windowed --noconsole --clean --noconfirm --noupx \
        ./asciiviewer.spec

    - name: Zip binary
      run: |
        cd ./dist/windows32
        zip asciiviewer-windows32.zip asciiviewer.exe

    - uses: actions/upload-artifact@v2
      with:
        name: asciiviewer-windows32
        path: ./dist/windows32/asciiviewer-windows32.zip

  release:
    needs: [ linux, macos, windows, wine ]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: actions/download-artifact@v1
        with:
          name: asciiviewer-linux
        continue-on-error: true

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asciiviewer-linux/asciiviewer-linux.zip
          asset_name: asciiviewer-linux-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
        continue-on-error: true

      - uses: actions/download-artifact@v1
        with:
          name: asciiviewer-macos
        continue-on-error: true

      - name: Upload MacOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asciiviewer-macos/asciiviewer-macos.zip
          asset_name: asciiviewer-macos-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
        continue-on-error: true

      - uses: actions/download-artifact@v1
        with:
          name: asciiviewer-windows64
        continue-on-error: true

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asciiviewer-windows64/asciiviewer-windows64.zip
          asset_name: asciiviewer-windows64-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
        continue-on-error: true

      - uses: actions/download-artifact@v1
        with:
          name: asciiviewer-windows32
        continue-on-error: true

      - name: checkin # DEBUG
        run: find .

      - name: Upload Wine Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asciiviewer-windows32/asciiviewer-windows32.zip
          asset_name: asciiviewer-windows32-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
        continue-on-error: true
